### ISSUE TITLE
bmake: -DMAKE_NATIVE prevents compilation

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#1]
bmake compiles with the compiler flag -DMAKE_NATIVE. As a result, all the source files include sys/cdefs.h under the assumption that the macro __COPYRIGHT is defined there.

sys/cdefs.h doesn't not include a definition for the __COPYRIGHT macro in the glibc version that I'm using (version 2.17, release 196.el7_4.2), nor in the latest version of glibc, glibc 2.28: [sys/cdefs.h](https://sourceware.org/git/?p=glibc.git;a=blob;f=misc/sys/cdefs.h;h=3f6fe3cc8563b49311327647fad53eb18d94da2c;hb=HEAD)

I managed to get bmake to compile by removing the -DMAKE_NATIVE compiler flag in [contrib/bmake/make-bootstrap.sh.in](https://github.com/arichardson/freebsd/blob/71b5b012c470799caab3128c9b365585d08aa7e2/contrib/bmake/make-bootstrap.sh.in#L14).

**Comment by arichardson** [comment]
I believe compilation will only succeed if you also have libbsd installed.

What distribution are you running? I can try to reproduce this using a docker image.

**Comment by alexandru-elisei** [comment]
The distribution I am using is Red Hat Enterprise Linux Server release 7.4 (Maipo). It's running on a cluster and I don't have root permission, nor access to libbsd.

**Comment by arichardson** [comment]
I just pushed some fixes that should hopefully address this issue. Could you retest with the latest version?
It will bootstrap libbsd if it doesn't exist now.

**Comment by alexandru-elisei** [comment]
It works with the latest patches, libbsd and bmake build successfully. I'll close this issue.
