### ISSUE TITLE
usr.sbin/btxld/elfh.c: Error: htole{16, 32}() do not expand to compile-time constant

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#10]
I ran into another problem, this time while compiling usr.sbin/btxld/elfh.c: [pastebin](https://pastebin.com/KZDTv7Dm)

The issue is that htole{16, 32} do not expand to compile time constants, but to inline functions in <bits/uintn-identity.h>.

libc version:
```
$ /lib/libc.so.6
GNU C Library (GNU libc) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.2.1 20180831.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.archlinux.org/>.
```
I managed to sidestep the issue by modifying the header file bits/uintn-identity.h and redefining the functions __uint{16, 32, 64}_identity to defines, instead of inline functions. I don't think that's the proper way to fix the problem though.

**Comment by arichardson** [comment]
Hmm I thought I had a workaround for this (but it might no longer work with newer glibc versions). I will try to build on a docker image using arch linux to reproduce.
