### ISSUE TITLE
Error linking ldd32.full: index past the index table in crt1.o

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#14]
I ran into this error: [pastebin](https://pastebin.com/JqpVMc0y).

I'm not sure what the problem is. It happened after about 25 minutes of compiling with -j4 on my Skylake 4C/4T laptop.

**Comment by arichardson** [comment]
I am also running into this error now. This seems to be a problem with lld 7.0.

See also  https://reviews.llvm.org/rL345002 (not included in 7.0)

A workaround for this would be to use -DWITHOUT_LIB32 which skips the whole lib32 compat libraries

**Comment by alexandru-elisei** [comment]
Building with -DWITHOUT_LIB32 was successful.

**Comment by arichardson** [comment]
LLVM 8.0 has been released.
