### ISSUE TITLE
bmake error: include/linux/unistd.h getentropy() redefined

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#16]
Hi,

I'm getting an error while trying to compile FreeBSD on Arch linux regarding redefining the function getentropy() from include/linux/unistd.h. Here's the complete log: [pastebin](https://pastebin.com/8J0RUnSE)

Clang version:
```
$ clang --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Libc version:
```
$ /usr/lib/libc.so.6 
GNU C Library (GNU libc) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.2.1 20180831.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.archlinux.org/>.
```
Was able to fix by commenting out the definition from include/linux/unistd.h.

**Comment by arichardson** [comment]
Fixed in https://github.com/arichardson/freebsd/commit/72129489287fb91a11e4d81aa067971c75112954
