### ISSUE TITLE
arm64: mIssing defines in lib/libcapsicum/capsicum_helpers.h

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#18]
When compiling for arm64 I  two undeclared identifier errors regarding TIOCGETA and FIODTYPE in lib/libcapsicum/capsicum_helpers.h: [arm64_missing_defines.log](https://github.com/arichardson/freebsd/files/3086682/arm64_missing_defines.log)

TIOCGETA is defined in the FreeBSD source in sys/sys/ttycom.h and FIODTYPE in sys/sys/filio.h, but I'm not sure how to include those headers.

EDIT: same environment as in #16.

**Comment by arichardson** [comment]
I just pushed some fixes for this, can you try again with latest HEAD?

**Comment by alexandru-elisei** [comment]
This issue was fixed, but now I can progress further into the compilation process and I am hitting the same issue as #17: [arm64_no_error_message.log](https://github.com/arichardson/freebsd/files/3086865/arm64_no_error_message.log)

**Comment by alexandru-elisei** [comment]
I'm reopening #17.
