### ISSUE TITLE
bmake error: don't know how to make sys/unknown/include/elf.h

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#3]
While trying to compile FreeBSD on linux I ran across a bmake error. This is the full log of the build: [pastebin](https://pastebin.com/EKXaeAV2).

As far as I can tell, the correct target architecture isn't picked up by the makefile and instead of trying to compile sys/amd64/include/elf.h, bmake searches for sys/unknown/include/elf.h.

Please let me know if there's something else you need.

**Comment by arichardson** [comment]
I just pushed a speculative fix. I can't reproduce this locally but maybe it fixes your issue.

**Comment by alexandru-elisei** [comment]
The error doesn't show up anymore. But now I'm running into another error, I'll open a separate issue for it.

You can close this issue if you want.
