### ISSUE TITLE
cross-build/include/linux/*: Error when including host /usr/include/bits/stat.h

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#4]
I'm getting an error each time the host /usr/include/bits/stat.h is included by the linux header files from tools/build/cross-build/include/linux. Here's the log: [pastebin](https://pastebin.com/27VJyusV)

I think the reason for the error is that __syscall_slong_t is not defined.

The variable is declared as unused, so as tried to get this issue by undefining \_\_x86_64__ just before including the file and then redefining it again. This is a diff of what I did: [pastebin](https://pastebin.com/EyLbnqSN)

It worked for sys/stat.h, but I don't think that's a proper fix for it, seems too hacky. Maybe define __syscall_slong_t to a long before including host /sys/include/bits/stat.h?

After the workaround, the exact same error came up again in tools/build/cross-build/include/linux/fcntl.h

**Comment by arichardson** [comment]
On my system this is defined in `/usr/include/x86_64-linux-gnu/bits/types.h`. 

I wonder if adding a `#include <sys/types.h>` in stat.h and fcntl.h before the `#include_next` woudl solve the issue?

**Comment by alexandru-elisei** [comment]
On my system it is defined in /usr/include/bits/types.h. The comment at the top of the files says to include sys/types if you want to include the file.

So I've tried adding #include <sys/types.h> before #include_next <sys/stat.h> in cross-build/include/linux/sys/stat.h, but I get the same error.

**Comment by arichardson** [comment]
The issue was due to a member in struct stat being called `__unused` which is a macro defined in sys/cdefs.h. I worked around this by undefining it before including sys/stat.h

**Comment by alexandru-elisei** [comment]
I can confirm it works now.
