### ISSUE TITLE
include/linux/limits.h: __USE_XOPEN and IOV_MAX not defined

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#7]
When building bmake I get two errors: "__USE_XOPEN not defined!" and "IOV_MAX should be defined". This is a log of the build: [pastebin](https://pastebin.com/ujFcJCmp).

I have bisected the problem and the commit that introduced the regression is 6545b17.

**Comment by arichardson** [comment]
Yes I added those as checks to avoid compilation errors later on. I guess the __USE_XOPEN can be removed but `#include_next` of limits.h should really define `IOV_MAX` otherwise the compilation will fail later on in the bootstrap phase (I can't remember which tool needs IOV_MAX).
Which version of glibc are you building with?

**Comment by alexandru-elisei** [comment]
It might be something wrong with my environment - clang runs into compile errors too.

I'll post an update once I find what's wrong.

**Comment by alexandru-elisei** [comment]
I tried building on my laptop, I still get the same error. I am using Arch Linux with all updates from 23 October 2018.

Here's my glibc version:
```
$ /lib/libc.so.6 
GNU C Library (GNU libc) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.2.1 20180831.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.archlinux.org/>.
```

From man 2 readv:

> POSIX.1  allows  an  implementation  to  place  a  limit on the number of items that can be passed in iov.  An implementation can advertise its limit by defining IOV_MAX in <limits.h> or at run time via the return value from sysconf(_SC_IOV_MAX).  On modern Linux systems, the limit is 1024.  Back in Linux 2.0 days, this limit was 16.

Perhaps defining IOV_MAX to 1024 can be used as a workaround?

**Comment by arichardson** [comment]
It should be possible to get the define from the system headers.

What does `grep -rn IOV_MAX /usr/include` say?

But I guess that workaround would also work.

**Comment by alexandru-elisei** [comment]
```
$ cat /usr/include/bits/xopen_lim.h
[..]
#include <bits/uio_lim.h>
#ifdef __IOV_MAX
# define IOV_MAX __IOV_MAX
#else
# undef IOV_MAX
#endif
[..]
```
```
$ cat /usr/include/bits/uio_limh.h
[..]
#ifndef _BITS_UIO_LIM_H
#define _BITS_UIO_LIM_H 1

/* Maximum length of the 'struct iovec' array in a single call to
   readv or writev.

   This macro has different values in different kernel versions.  The
   latest versions of the kernel use 1024 and this is good choice.  Since
   the C library implementation of readv/writev is able to emulate the
   functionality even if the currently running kernel does not support
   this large value the readv/writev call will not fail because of this.  */
#define __IOV_MAX	1024

#endif
```
```
$ grep -rn 'include <bits/xopen_lim.h>' /usr/include
/usr/include/limits.h:191:# include <bits/xopen_lim.h>
```
EDIT:
```
$ cat /usr/include/limits.h
[..]
#ifdef	__USE_XOPEN
# include <bits/xopen_lim.h>
#endif
```
So I guess the problem is the fact that __USE_XOPEN is not defined.

**Comment by alexandru-elisei** [comment]
After more digging:
```
$ grep -nB1 __USE_XOPEN /usr/include/features.h
[..]
329-#ifdef	_XOPEN_SOURCE
330:# define __USE_XOPEN	1
```
I did a grep for _XOPEN_SOURCE in /usr/include and as far as I can tell this is something that the compiler defines.
