### ISSUE TITLE
contrib/mknod/pack_dev.c: Wrong header file for makedev(), major() and minor()

### ISSUE THREAD

**Issue by alexandru-elisei** [arichardson/freebsd#9]
The functions makedev(), major() and minor() aren't declared in any of the headers included in contrib/mknod/pack_dev.c: [pastebin](https://pastebin.com/Fcq0kPEa)

From man 3 makedev:
```
SYNOPSIS
       #include <sys/sysmacros.h>

       dev_t makedev(unsigned int maj, unsigned int min);

       unsigned int major(dev_t dev);
       unsigned int minor(dev_t dev);
```

The problem was fixed by adding `#include <sys/sysmacros.h>` to contrib/mknod/pack_dev.c.

**Comment by arichardson** [comment]
On FreeBSD it seems to be part of `<sys/types.h>`. I'll add a workaround to the compat headers.
